import { resultSuccess } from '../../mock/_util';
import { MockMethod } from 'vite-plugin-mock';
import { any } from 'vue-types';

// admin页 end
export default [
  /**
   * 获取账套列表
   */
  // {
  //   url: '/api/sys/account/findAll',
  //   timeout: 0,
  //   method: 'get',
  //   response: ({ query }) => {
  //     return {
  //       code: 0,
  //       type: 'success',
  //       message: 'ok',
  //       result: {
  //         items: [
  //           // {
  //           //   createdAt: null,
  //           //   modifiedAt: '2021-05-16T10:45:56.89394',
  //           //   createdBy: null,
  //           //   modifiedBy: 1393759594936930304,
  //           //   id: '1',
  //           //   uniqueCode: 'abc001',
  //           //   accId: 'deptprohs-001-2021',
  //           //   accName: '部门项目核算',
  //           //   uniqueAccStandard: null,
  //           //   iyear: '2021',
  //           //   imonth: '1',
  //           //   abbreviation: null,
  //           //   uniqueUserCode: null,
  //           //   iperiod: null,
  //           //   defaultLanguage: null,
  //           //   industryClassCode: null,
  //           //   industryCode: null,
  //           //   kemuJici: null,
  //           //   flag: '1',
  //           //   beiyong1: null,
  //           //   beiyong2: null,
  //           //   beiyong3: null,
  //           // },
  //           {
  //             createdAt: null,
  //             modifiedAt: '2021-05-16T10:45:56.89394',
  //             createdBy: null,
  //             modifiedBy: 1393759594936930304,
  //             id: '2',
  //             uniqueCode: 'abc001',
  //             accId: 'bjxgkj-001-2021',
  //             accName: '北京希格科技',
  //             uniqueAccStandard: null,
  //             iyear: '2021',
  //             imonth: '1',
  //             abbreviation: null,
  //             uniqueUserCode: null,
  //             iperiod: null,
  //             defaultLanguage: null,
  //             industryClassCode: null,
  //             industryCode: null,
  //             kemuJici: null,
  //             flag: '1',
  //             beiyong1: null,
  //             beiyong2: null,
  //             beiyong3: null,
  //           },
  //           {
  //             createdAt: null,
  //             modifiedAt: null,
  //             createdBy: null,
  //             modifiedBy: null,
  //             id: '4',
  //             uniqueCode: '6086609ff14c4fea8652d2c5',
  //             accId: '002',
  //             accName: '测试',
  //             uniqueAccStandard: null,
  //             iyear: '',
  //             imonth: '',
  //             abbreviation: null,
  //             uniqueUserCode: null,
  //             iperiod: null,
  //             defaultLanguage: '',
  //             industryClassCode: null,
  //             industryCode: null,
  //             kemuJici: null,
  //             flag: '1',
  //             beiyong1: null,
  //             beiyong2: null,
  //             beiyong3: null,
  //           },
  //           {
  //             createdAt: null,
  //             modifiedAt: null,
  //             createdBy: null,
  //             modifiedBy: null,
  //             id: '1386572772871901184',
  //             uniqueCode: '60866224f14c8c7e33463b7a',
  //             accId: '003',
  //             accName: '测试3',
  //             uniqueAccStandard: null,
  //             iyear: '',
  //             imonth: '',
  //             abbreviation: null,
  //             uniqueUserCode: null,
  //             iperiod: null,
  //             defaultLanguage: '',
  //             industryClassCode: null,
  //             industryCode: null,
  //             kemuJici: null,
  //             flag: '1',
  //             beiyong1: null,
  //             beiyong2: null,
  //             beiyong3: null,
  //           },
  //           {
  //             createdAt: '2021-04-26T00:00:00',
  //             modifiedAt: '2021-04-26T00:00:00',
  //             createdBy: 1386576282023759872,
  //             modifiedBy: 1386576282023759872,
  //             id: '1386576282023759872',
  //             uniqueCode: '60866569f14cab7e7a59c35a',
  //             accId: '123',
  //             accName: '123',
  //             uniqueAccStandard: null,
  //             iyear: '',
  //             imonth: '',
  //             abbreviation: null,
  //             uniqueUserCode: null,
  //             iperiod: null,
  //             defaultLanguage: '',
  //             industryClassCode: null,
  //             industryCode: null,
  //             kemuJici: null,
  //             flag: '1',
  //             beiyong1: null,
  //             beiyong2: null,
  //             beiyong3: null,
  //           },
  //           {
  //             createdAt: '2021-04-26T00:00:00',
  //             modifiedAt: '2021-05-11T14:38:26.309448',
  //             createdBy: 1386576616032964600,
  //             modifiedBy: 1392006163708645376,
  //             id: '1386576616032964608',
  //             uniqueCode: '608665b9f14cd88dbf546f24',
  //             accId: '1231',
  //             accName: '12321',
  //             uniqueAccStandard: null,
  //             iyear: '',
  //             imonth: '',
  //             abbreviation: null,
  //             uniqueUserCode: null,
  //             iperiod: null,
  //             defaultLanguage: '',
  //             industryClassCode: null,
  //             industryCode: null,
  //             kemuJici: null,
  //             flag: '1',
  //             beiyong1: null,
  //             beiyong2: null,
  //             beiyong3: null,
  //           },
  //         ],
  //         total: 5,
  //       },
  //       list: null,
  //     };
  //   },
  // },
] as MockMethod[];

// 进入总账模块，选择年度，选择公司, 默认登陆时间,默认第一个公司,确定后,设置全局schemaName=公司名 + 登陆日期年度 bjxgkj-001-2025,  是否有
//
