const columnPropertyModel = {
  'xs-arrive':{
    core:{
      templateType:'0',
      templateSort:'0',
      templateName:'系统模板',
      templateBelong:'xs-arrive',
    },
    list:[
      {
        systemName:'销货单',
        printName:'销货单',
        alignWay:'center',
        printWidth:'100',
        fontSize:'20',
        belongArea:'0',
        paintSort:'0',
        propertyName: 'tableTitle',
        isPrint: true,
      }, {
        systemName:'销货单号',
        printName:'销货单号',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'0',
        propertyName: 'ccode',
        isPrint: true,
      },{
        systemName:'单据日期',
        printName:'单据日期',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'1',
        propertyName: 'ddate',
        isPrint: true,
      },{
        systemName:'销售客户',
        printName:'销售客户',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'2',
        propertyName: 'cvencode',
        isPrint: true,
      },{
        systemName:'结算客户',
        printName:'结算客户',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'3',
        propertyName: 'cvencodeJs',
        isPrint: true,
      },{
        systemName:'仓库',
        printName:'仓库',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'4',
        propertyName: 'cwhcode',
        isPrint: true,
      },{
        systemName:'业务部门',
        printName:'业务部门',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'5',
        propertyName: 'cdepcode',
        isPrint: true,
      },{
        systemName:'业务员',
        printName:'业务员',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'6',
        propertyName: 'cpersoncode',
        isPrint: true,
      },{
        systemName:'质检员',
        printName:'质检员',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'7',
        propertyName: 'sgspperson',
        isPrint: true,
      },{
        systemName:'送货人',
        printName:'送货人',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'8',
        propertyName: 'deliveryUser',
        isPrint: true,
      },{
        systemName:'销售税率',
        printName:'销售税率',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'9',
        propertyName: 'xsRate',
        isPrint: true,
      },{
        systemName:'票据类型',
        printName:'票据类型',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'10',
        propertyName: 'invoiceStyle',
        isPrint: true,
      },{
        systemName:'备注',
        printName:'备注',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'11',
        propertyName: 'cmemo',
        isPrint: true,
      },{
        systemName:'序号',
        printName:'序号',
        alignWay:'center',
        printWidth:'12',
        fontSize:'8',
        belongArea:'2',
        paintSort:'0',
        propertyName: 'index',
        isPrint: true,
      },{
        systemName:'仓储位置',
        printName:'仓储位置',
        alignWay:'center',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'1',
        propertyName: 'cwhcode',
        isPrint: true,
      },{
        systemName:'条形码',
        printName:'条形码',
        alignWay:'left',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'2',
        propertyName: 'cinvodeBarcode',
        isPrint: false,
      },{
        systemName:'存货编码',
        printName:'存货编码',
        alignWay:'left',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'3',
        propertyName: 'cinvode',
        isPrint: true,
      },{
        systemName:'存货名称',
        printName:'存货名称',
        alignWay:'left',
        printWidth:'35',
        fontSize:'8',
        belongArea:'2',
        paintSort:'4',
        propertyName: 'cinvodeName',
        isPrint: true,
      },{
        systemName:'规格型号',
        printName:'规格型号',
        alignWay:'left',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'5',
        propertyName: 'cinvodeType',
        isPrint: true,
      },
      {
        systemName:'计量单位',
        printName:'单位',
        alignWay:'center',
        printWidth:'15',
        fontSize:'8',
        belongArea:'2',
        paintSort:'6',
        propertyName: 'xsUnitId',
        isPrint: true,
      },{
        systemName:'数量',
        printName:'数量',
        alignWay:'center',
        printWidth:'15',
        fontSize:'8',
        belongArea:'2',
        paintSort:'7',
        propertyName: 'quantity',
        isPrint: true,
      },
      {
        systemName:'主计量',
        printName:'主计量',
        alignWay:'center',
        printWidth:'15',
        fontSize:'8',
        belongArea:'2',
        paintSort:'8',
        propertyName: 'cunitid',
        isPrint: false,
      },{
        systemName:'主数量',
        printName:'主数量',
        alignWay:'center',
        printWidth:'15',
        fontSize:'8',
        belongArea:'2',
        paintSort:'9',
        propertyName: 'baseQuantity',
        isPrint: false,
      },
      {
        systemName:'税率',
        printName:'税率',
        alignWay:'center',
        printWidth:'15',
        fontSize:'8',
        belongArea:'2',
        paintSort:'10',
        propertyName: 'itaxrate',
        isPrint: false,
      },
      {
        systemName:'无税单价',
        printName:'无税单价',
        alignWay:'right',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'11',
        propertyName: 'price',
        isPrint: false,
      },
      {
        systemName:'无税金额',
        printName:'无税金额',
        alignWay:'right',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'12',
        propertyName: 'icost',
        isPrint: false,
      },
      {
        systemName:'税额',
        printName:'税额',
        alignWay:'right',
        printWidth:'15',
        fontSize:'8',
        belongArea:'2',
        paintSort:'13',
        propertyName: 'itaxprice',
        isPrint: false,
      },
      {
        systemName:'含税单价',
        printName:'含税单价',
        alignWay:'right',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'14',
        propertyName: 'taxprice',
        isPrint: true,
      },{
        systemName:'价税合计',
        printName:'价税合计',
        alignWay:'right',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'15',
        propertyName: 'isum',
        isPrint: true,
      },{
        systemName:'批号',
        printName:'批号',
        alignWay:'left',
        printWidth:'15',
        fontSize:'8',
        belongArea:'2',
        paintSort:'16',
        propertyName: 'batchId',
        isPrint: true,
      },
      {
        systemName:'赠品',
        printName:'赠品',
        alignWay:'left',
        printWidth:'15',
        fontSize:'8',
        belongArea:'2',
        paintSort:'17',
        propertyName: 'isGive',
        isPrint: false,
      },
      {
        systemName:'生效日期',
        printName:'生效日期',
        alignWay:'center',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'18',
        propertyName: 'dpdate',
        isPrint: false,
      },
      {
        systemName:'失效日期',
        printName:'失效日期',
        alignWay:'center',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'19',
        propertyName: 'dvdate',
        isPrint: true,
      },{
        systemName:'备注',
        printName:'备注',
        alignWay:'left',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'20',
        propertyName: 'cmemo',
        isPrint: false,
      },{
        systemName:'制单',
        printName:'制单',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'3',
        paintSort:'0',
        propertyName: 'cmaker',
        isPrint: true,
      },{
        systemName:'审核',
        printName:'审核',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'3',
        paintSort:'1',
        propertyName: 'bcheckUser',
        isPrint: true,
      },{
        systemName:'页码',
        printName:'页码',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'3',
        paintSort:'2',
        propertyName: 'index',
        isPrint: true,
      }
    ]
  },
  'cg-arrive':{
    core:{
      templateType:'0',
      templateSort:'0',
      templateName:'系统模板',
      templateBelong:'cg-arrive',
    },
    list:[
      {
        systemName:'采购到货单',
        printName:'采购到货单',
        alignWay:'center',
        printWidth:'100',
        fontSize:'20',
        belongArea:'0',
        paintSort:'0',
        propertyName: 'tableTitle',
        isPrint: true,
      }, {
        systemName:'单据编号',
        printName:'单据编号',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'0',
        propertyName: 'ccode',
        isPrint: true,
      },{
        systemName:'单据日期',
        printName:'单据日期',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'1',
        propertyName: 'ddate',
        isPrint: true,
      },{
        systemName:'供应商',
        printName:'供应商',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'2',
        propertyName: 'cvencode',
        isPrint: true,
      },{
        systemName:'结算供应商',
        printName:'结算供应商',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'3',
        propertyName: 'cvencodeJs',
        isPrint: true,
      },{
        systemName:'仓库',
        printName:'仓库',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'4',
        propertyName: 'cwhcode',
        isPrint: true,
      },{
        systemName:'业务部门',
        printName:'业务部门',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'5',
        propertyName: 'cdepcode',
        isPrint: true,
      },{
        systemName:'业务员',
        printName:'业务员',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'6',
        propertyName: 'cpersoncode',
        isPrint: true,
      },{
        systemName:'税率',
        printName:'税率',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'7',
        propertyName: 'rate',
        isPrint: true,
      },{
        systemName:'备注',
        printName:'备注',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'8',
        propertyName: 'cmemo',
        isPrint: true,
      },


      {
        systemName:'序号',
        printName:'序号',
        alignWay:'center',
        printWidth:'12',
        fontSize:'8',
        belongArea:'2',
        paintSort:'0',
        propertyName: 'index',
        isPrint: true,
      },{
        systemName:'仓储位置',
        printName:'仓储位置',
        alignWay:'center',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'1',
        propertyName: 'cwhcode',
        isPrint: true,
      },{
        systemName:'条形码',
        printName:'条形码',
        alignWay:'left',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'2',
        propertyName: 'cinvodeBarcode',
        isPrint: false,
      },{
        systemName:'存货编码',
        printName:'存货编码',
        alignWay:'left',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'3',
        propertyName: 'cinvode',
        isPrint: true,
      },{
        systemName:'存货名称',
        printName:'存货名称',
        alignWay:'left',
        printWidth:'35',
        fontSize:'8',
        belongArea:'2',
        paintSort:'4',
        propertyName: 'cinvodeName',
        isPrint: true,
      },{
        systemName:'规格型号',
        printName:'规格型号',
        alignWay:'left',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'5',
        propertyName: 'cinvodeType',
        isPrint: true,
      },
      {
        systemName:'计量单位',
        printName:'单位',
        alignWay:'center',
        printWidth:'15',
        fontSize:'8',
        belongArea:'2',
        paintSort:'6',
        propertyName: 'xsUnitId',
        isPrint: true,
      },{
        systemName:'数量',
        printName:'数量',
        alignWay:'center',
        printWidth:'15',
        fontSize:'8',
        belongArea:'2',
        paintSort:'7',
        propertyName: 'quantity',
        isPrint: true,
      },
      {
        systemName:'主计量',
        printName:'主计量',
        alignWay:'center',
        printWidth:'15',
        fontSize:'8',
        belongArea:'2',
        paintSort:'8',
        propertyName: 'cunitid',
        isPrint: false,
      },{
        systemName:'主数量',
        printName:'主数量',
        alignWay:'center',
        printWidth:'15',
        fontSize:'8',
        belongArea:'2',
        paintSort:'9',
        propertyName: 'baseQuantity',
        isPrint: false,
      },
      {
        systemName:'税率',
        printName:'税率',
        alignWay:'center',
        printWidth:'15',
        fontSize:'8',
        belongArea:'2',
        paintSort:'10',
        propertyName: 'itaxrate',
        isPrint: true,
      },
      {
        systemName:'含税单价',
        printName:'含税单价',
        alignWay:'right',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'11',
        propertyName: 'taxprice',
        isPrint: false,
      },
      {
        systemName:'价税合计',
        printName:'价税合计',
        alignWay:'right',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'12',
        propertyName: 'isum',
        isPrint: false,
      },
      {
        systemName:'税额',
        printName:'税额',
        alignWay:'right',
        printWidth:'15',
        fontSize:'8',
        belongArea:'2',
        paintSort:'13',
        propertyName: 'itaxprice',
        isPrint: false,
      },
      {
        systemName:'含税单价',
        printName:'含税单价',
        alignWay:'right',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'14',
        propertyName: 'taxprice',
        isPrint: true,
      },{
        systemName:'价税合计',
        printName:'价税合计',
        alignWay:'right',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'15',
        propertyName: 'isum',
        isPrint: true,
      },{
        systemName:'批号',
        printName:'批号',
        alignWay:'left',
        printWidth:'15',
        fontSize:'8',
        belongArea:'2',
        paintSort:'16',
        propertyName: 'batchId',
        isPrint: true,
      },
      {
        systemName:'赠品',
        printName:'赠品',
        alignWay:'left',
        printWidth:'15',
        fontSize:'8',
        belongArea:'2',
        paintSort:'17',
        propertyName: 'isGive',
        isPrint: false,
      },
      {
        systemName:'生效日期',
        printName:'生效日期',
        alignWay:'center',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'18',
        propertyName: 'dpdate',
        isPrint: false,
      },
      {
        systemName:'失效日期',
        printName:'失效日期',
        alignWay:'center',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'19',
        propertyName: 'dvdate',
        isPrint: true,
      },{
        systemName:'备注',
        printName:'备注',
        alignWay:'left',
        printWidth:'20',
        fontSize:'8',
        belongArea:'2',
        paintSort:'20',
        propertyName: 'cmemo',
        isPrint: false,
      },{
        systemName:'制单人',
        printName:'制单人',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'3',
        paintSort:'0',
        propertyName: 'cmaker',
        isPrint: true,
      },{
        systemName:'审核人',
        printName:'审核人',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'3',
        paintSort:'1',
        propertyName: 'bcheckUser',
        isPrint: true,
      },{
        systemName:'页码',
        printName:'页码',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'3',
        paintSort:'2',
        propertyName: 'index',
        isPrint: true,
      }
    ]
  },
  'kc-cgDepot':{
    core:{
      templateType:'0',
      templateSort:'0',
      templateName:'系统模板',
      templateBelong:'kc-cgDepot',
    },
    list:[
      {
        systemName:'采购入库单',
        printName:'采购入库单',
        alignWay:'center',
        printWidth:'100',
        fontSize:'20',
        belongArea:'0',
        paintSort:'0',
        propertyName: 'tableTitle',
        isPrint: true,
      }, {
        systemName:'单据编号',
        printName:'单据编号',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'0',
        propertyName: 'ccode',
        isPrint: true,
      },{
        systemName:'单据日期',
        printName:'单据日期',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'1',
        propertyName: 'ddate',
        isPrint: true,
      },{
        systemName:'供应商',
        printName:'供应商',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'2',
        propertyName: 'cvencode',
        isPrint: true,
      },{
        systemName:'结算供应商',
        printName:'结算供应商',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'3',
        propertyName: 'cvencodeJs',
        isPrint: true,
      },{
        systemName:'仓库',
        printName:'仓库',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'4',
        propertyName: 'cwhcode',
        isPrint: true,
      },{
        systemName:'业务部门',
        printName:'业务部门',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'5',
        propertyName: 'cdepcode',
        isPrint: false,
      },{
        systemName:'业务员',
        printName:'业务员',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'6',
        propertyName: 'cpersoncode',
        isPrint: true,
      },{
        systemName:'库管员',
        printName:'库管员',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'7',
        propertyName: 'cwhcodeUser',
        isPrint: true,
      },{
        systemName:'税率',
        printName:'税率',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'8',
        propertyName: 'rate',
        isPrint: false,
      },{
        systemName:'备注',
        printName:'备注',
        alignWay:'left',
        printWidth:'100',
        fontSize:'9',
        belongArea:'1',
        paintSort:'8',
        propertyName: 'cmemo',
        isPrint: true,
      },

      {
        systemName:'序号',
        printName:'序号',
        alignWay:'center',
        printWidth:'13',
        fontSize:'9',
        belongArea:'2',
        paintSort:'0',
        propertyName: 'index',
        isPrint: true,
      },{
        systemName:'仓储位置',
        printName:'仓储位置',
        alignWay:'left',
        printWidth:'20',
        fontSize:'9',
        belongArea:'2',
        paintSort:'1',
        propertyName: 'cwhcode',
        isPrint: true,
      },{
        systemName:'存货编码',
        printName:'存货编码',
        alignWay:'left',
        printWidth:'25',
        fontSize:'9',
        belongArea:'2',
        paintSort:'2',
        propertyName: 'cinvode',
        isPrint: true,
      },{
        systemName:'存货名称',
        printName:'存货名称',
        alignWay:'left',
        printWidth:'40',
        fontSize:'9',
        belongArea:'2',
        paintSort:'3',
        propertyName: 'cinvodeName',
        isPrint: true,
      },{
        systemName:'条形码',
        printName:'条形码',
        alignWay:'left',
        printWidth:'20',
        fontSize:'9',
        belongArea:'2',
        paintSort:'4',
        propertyName: 'bcheck1',
        isPrint: true,
      },{
        systemName:'规格型号',
        printName:'规格型号',
        alignWay:'left',
        printWidth:'20',
        fontSize:'9',
        belongArea:'2',
        paintSort:'5',
        propertyName: 'cinvodeType',
        isPrint: true,
      },{
        systemName:'计量单位',
        printName:'计量单位',
        alignWay:'center',
        printWidth:'20',
        fontSize:'9',
        belongArea:'2',
        paintSort:'6',
        propertyName: 'cgUnitId',
        isPrint: true,
      },{
        systemName:'数量',
        printName:'数量',
        alignWay:'right',
        printWidth:'15',
        fontSize:'9',
        belongArea:'2',
        paintSort:'7',
        propertyName: 'cnumber',
        isPrint: true,
      },{
        systemName:'无税单价',
        printName:'无税单价',
        alignWay:'right',
        printWidth:'20',
        fontSize:'9',
        belongArea:'2',
        paintSort:'8',
        propertyName: 'price',
        isPrint: true,
      },{
        systemName:'无税金额',
        printName:'无税金额',
        alignWay:'right',
        printWidth:'20',
        fontSize:'9',
        belongArea:'2',
        paintSort:'9',
        propertyName: 'icost',
        isPrint: true,
      },{
        systemName:'批号',
        printName:'批号',
        alignWay:'left',
        printWidth:'20',
        fontSize:'9',
        belongArea:'2',
        paintSort:'10',
        propertyName: 'batchId',
        isPrint: true,
      },{
        systemName:'失效日期',
        printName:'失效日期',
        alignWay:'center',
        printWidth:'23',
        fontSize:'9',
        belongArea:'2',
        paintSort:'11',
        propertyName: 'dvdate',
        isPrint: true,
      },{
        systemName:'备注',
        printName:'备注',
        alignWay:'left',
        printWidth:'20',
        fontSize:'9',
        belongArea:'2',
        paintSort:'12',
        propertyName: 'cmemo',
        isPrint: true,
      },{
        systemName:'制表人',
        printName:'制表人',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'3',
        paintSort:'0',
        propertyName: 'cmaker',
        isPrint: true,
      },{
        systemName:'审核人',
        printName:'审核人',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'3',
        paintSort:'1',
        propertyName: 'bcheckUser',
        isPrint: true,
      },{
        systemName:'',
        printName:'',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'3',
        paintSort:'3',
        propertyName: '',
        isPrint: true,
      },{
        systemName:'页码',
        printName:'页码',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'3',
        paintSort:'4',
        propertyName: 'index',
        isPrint: true,
      }
    ]
  },
  'kc-qtDepot':{
    core:{
      templateType:'0',
      templateSort:'0',
      templateName:'系统模板',
      templateBelong:'kc-qtDepot',
    },
    list:[
      {
        systemName:'其他入库单',
        printName:'其他入库单',
        alignWay:'center',
        printWidth:'100',
        fontSize:'20',
        belongArea:'0',
        paintSort:'0',
        propertyName: 'tableTitle',
        isPrint: true,
      }, {
        systemName:'单据编号',
        printName:'单据编号',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'0',
        propertyName: 'ccode',
        isPrint: true,
      },{
        systemName:'单据日期',
        printName:'单据日期',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'1',
        propertyName: 'ddate',
        isPrint: true,
      },{
        systemName:'单据类型',
        printName:'单据类型',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'2',
        propertyName: 'unitType',
        isPrint: true,
      },{
        systemName:'业务单位',
        printName:'业务单位',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'3',
        propertyName: 'unitValue',
        isPrint: true,
      },{
        systemName:'仓库',
        printName:'仓库',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'4',
        propertyName: 'cwhcode',
        isPrint: true,
      },{
        systemName:'业务部门',
        printName:'业务部门',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'5',
        propertyName: 'cdepcode',
        isPrint: true,
      },{
        systemName:'业务员',
        printName:'业务员',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'1',
        paintSort:'6',
        propertyName: 'cpersoncode',
        isPrint: true,
      },{
        systemName:'备注',
        printName:'备注',
        alignWay:'left',
        printWidth:'100',
        fontSize:'9',
        belongArea:'1',
        paintSort:'8',
        propertyName: 'cmemo',
        isPrint: true,
      },

      {
        systemName:'序号',
        printName:'序号',
        alignWay:'center',
        printWidth:'13',
        fontSize:'9',
        belongArea:'2',
        paintSort:'0',
        propertyName: 'index',
        isPrint: true,
      },{
        systemName:'仓储位置',
        printName:'仓储位置',
        alignWay:'left',
        printWidth:'20',
        fontSize:'9',
        belongArea:'2',
        paintSort:'1',
        propertyName: 'cwhcode',
        isPrint: true,
      },{
        systemName:'存货编码',
        printName:'存货编码',
        alignWay:'left',
        printWidth:'25',
        fontSize:'9',
        belongArea:'2',
        paintSort:'2',
        propertyName: 'cinvode',
        isPrint: true,
      },{
        systemName:'存货名称',
        printName:'存货名称',
        alignWay:'left',
        printWidth:'40',
        fontSize:'9',
        belongArea:'2',
        paintSort:'3',
        propertyName: 'cinvodeName',
        isPrint: true,
      },{
        systemName:'条形码',
        printName:'条形码',
        alignWay:'left',
        printWidth:'20',
        fontSize:'9',
        belongArea:'2',
        paintSort:'4',
        propertyName: 'bcheck1',
        isPrint: true,
      },{
        systemName:'规格型号',
        printName:'规格型号',
        alignWay:'left',
        printWidth:'20',
        fontSize:'9',
        belongArea:'2',
        paintSort:'5',
        propertyName: 'cinvodeType',
        isPrint: true,
      },{
        systemName:'计量单位',
        printName:'计量单位',
        alignWay:'center',
        printWidth:'20',
        fontSize:'9',
        belongArea:'2',
        paintSort:'6',
        propertyName: 'cgUnitId',
        isPrint: true,
      },{
        systemName:'数量',
        printName:'数量',
        alignWay:'right',
        printWidth:'15',
        fontSize:'9',
        belongArea:'2',
        paintSort:'7',
        propertyName: 'cnumber',
        isPrint: true,
      },{
        systemName:'无税单价',
        printName:'无税单价',
        alignWay:'right',
        printWidth:'20',
        fontSize:'9',
        belongArea:'2',
        paintSort:'8',
        propertyName: 'price',
        isPrint: true,
      },{
        systemName:'无税金额',
        printName:'无税金额',
        alignWay:'right',
        printWidth:'20',
        fontSize:'9',
        belongArea:'2',
        paintSort:'9',
        propertyName: 'icost',
        isPrint: true,
      },{
        systemName:'批号',
        printName:'批号',
        alignWay:'left',
        printWidth:'20',
        fontSize:'9',
        belongArea:'2',
        paintSort:'10',
        propertyName: 'batchId',
        isPrint: true,
      },{
        systemName:'失效日期',
        printName:'失效日期',
        alignWay:'center',
        printWidth:'23',
        fontSize:'9',
        belongArea:'2',
        paintSort:'11',
        propertyName: 'dvdate',
        isPrint: true,
      },{
        systemName:'备注',
        printName:'备注',
        alignWay:'left',
        printWidth:'20',
        fontSize:'9',
        belongArea:'2',
        paintSort:'12',
        propertyName: 'cmemo',
        isPrint: true,
      },{
        systemName:'制表人',
        printName:'制表人',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'3',
        paintSort:'0',
        propertyName: 'cmaker',
        isPrint: true,
      },{
        systemName:'审核人',
        printName:'审核人',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'3',
        paintSort:'1',
        propertyName: 'bcheckUser',
        isPrint: true,
      },{
        systemName:'',
        printName:'',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'3',
        paintSort:'3',
        propertyName: '',
        isPrint: true,
      },{
        systemName:'页码',
        printName:'页码',
        alignWay:'left',
        printWidth:'100',
        fontSize:'10',
        belongArea:'3',
        paintSort:'4',
        propertyName: 'index',
        isPrint: true,
      }
    ]
  },
}


export function getTempProperty(key) {
  return columnPropertyModel[key]
}
